---
name: End to End Full

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  e2e:
    name: E2E
    timeout-minutes: 120
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Run most tests against the latest K8s version
        k8s_version: ['1.23']
        lighthouse: ['', 'lighthouse']
    steps:
      - name: Check out the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          k8s_version: ${{ matrix.k8s_version }}
          using: ${{ matrix.globalnet }} ${{ matrix.lighthouse }} ${{ matrix.ovn }}

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
